name: raspberry_pi_3

layers:
  - uri: git://git.yoctoproject.org/poky
    revision: dunfell

  - uri: git://git.openembedded.org/meta-openembedded
    revision: dunfell

bitbake:
  image: core-image-base
  source:
    call: oe-init-build-env
    path: ./layers/poky

