name: Build Zynq-Generic image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  yocto-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Yocto Docker Image
        run: |
          ls -lash
          tree -L 4
          docker build -t yocto-builder docker/Dockerfile.yocto

      - name: Run Yocto Build
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/workspace -w /workspace/work yocto-builder /bin/bash -c "
          source setupsdk && cd build &&
          bitbake-layers add-layer bitbake-layers add-layer ../layers/meta-artyz7 &&
          echo 'MACHINE = \"zynq-generic\"' >> conf/local.conf &&
          echo 'BB_NUMBER_THREADS = \"$(nproc)\"' >> conf/local.conf &&
          echo 'PARALLEL_MAKE = \"-j$(nproc)\"' >> conf/local.conf &&
          bitbake petalinux-image-minimal"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BOOT.bin
          path: build/tmp/deploy/images/zynq-generic/boot.bin
