name: Run Python Unit Tests

on:
  push:
    branches:
      - raspberry_pi
  pull_request:
    branches:
      - raspberry_pi

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Fetch all history so tags are available
          fetch-tags: true # Ensure tags are fetched

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: |
          make coverage 2>&1 | tee coverage.log
          echo "### Coverage Report" >> $GITHUB_STEP_SUMMARY
          cat coverage_output.log >> $GITHUB_STEP_SUMMARY
