name: Run Python Unit Tests

on:
  push:
    branches:
      - raspberry_pi
  pull_request:
    branches:
      - raspberry_pi

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version that matches your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          make run_all_unit_tests
