name: Run Python Unit Tests

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - requirements-dev.txt
      - requirements.txt
      - setup.py
      - .github/workflows/run_python_tests.yml


jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Fetch all history so tags are available
          fetch-tags: true # Ensure tags are fetched

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: |
          make coverage 2>&1 | tee coverage.log

          python3 scripts/pytest_cov_to_md.py --file coverage.log | tee -a report.md

          cat report.md >> $GITHUB_STEP_SUMMARY

          if grep -q "FAILED" coverage.log; then
            echo "Unit tests failed. Check the logs above."
            exit 1
          else
            echo "All unit tests passed."
          fi
